-- 1. CLEANUP
DROP TABLE IF EXISTS meal_items CASCADE;
DROP TABLE IF EXISTS meals CASCADE;
DROP TABLE IF EXISTS days CASCADE;
DROP TABLE IF EXISTS weeks CASCADE;
DROP TABLE IF EXISTS diets CASCADE;
DROP TABLE IF EXISTS foods CASCADE;

-- 2. FOODS (Common catalog)
CREATE TABLE foods (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  unit TEXT NOT NULL,
  calories NUMERIC DEFAULT 0,
  protein NUMERIC DEFAULT 0,
  carbs NUMERIC DEFAULT 0,
  fats NUMERIC DEFAULT 0,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. DIETS
CREATE TABLE diets (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  target_calories NUMERIC DEFAULT 0,
  target_protein NUMERIC DEFAULT 0,
  target_carbs NUMERIC DEFAULT 0,
  target_fats NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. WEEKS
CREATE TABLE weeks (
  id TEXT PRIMARY KEY,
  diet_id TEXT REFERENCES diets(id) ON DELETE CASCADE NOT NULL,
  week_number INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. DAYS
CREATE TABLE days (
  id TEXT PRIMARY KEY,
  week_id TEXT REFERENCES weeks(id) ON DELETE CASCADE NOT NULL,
  day_of_week INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. MEALS
CREATE TABLE meals (
  id TEXT PRIMARY KEY,
  day_id TEXT REFERENCES days(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. MEAL ITEMS (Linking foods to meals)
CREATE TABLE meal_items (
  id TEXT PRIMARY KEY,
  meal_id TEXT REFERENCES meals(id) ON DELETE CASCADE NOT NULL,
  food_id TEXT REFERENCES foods(id) ON DELETE CASCADE NOT NULL,
  quantity NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. OPEN ACCESS
ALTER TABLE foods ENABLE ROW LEVEL SECURITY;
ALTER TABLE diets ENABLE ROW LEVEL SECURITY;
ALTER TABLE weeks ENABLE ROW LEVEL SECURITY;
ALTER TABLE days ENABLE ROW LEVEL SECURITY;
ALTER TABLE meals ENABLE ROW LEVEL SECURITY;
ALTER TABLE meal_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow All" ON foods FOR ALL USING (true);
CREATE POLICY "Allow All" ON diets FOR ALL USING (true);
CREATE POLICY "Allow All" ON weeks FOR ALL USING (true);
CREATE POLICY "Allow All" ON days FOR ALL USING (true);
CREATE POLICY "Allow All" ON meals FOR ALL USING (true);
CREATE POLICY "Allow All" ON meal_items FOR ALL USING (true);
